In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler,Normalizer,Binarizer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif,RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
df = pd.read_csv('/content/pima-indians-diabetes.data.csv',header=None)
df.head(5)

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [ ]:
array=df.values

In [ ]:
X=array[:,0:-1]
Y=array[:,-1]

In [ ]:
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(X)

In [ ]:
np.set_printoptions(precision=3) 

In [ ]:
rescaledX[0:5,:]

array([[0.353, 0.744, 0.59 , 0.354, 0.   , 0.501, 0.234, 0.483],
       [0.059, 0.427, 0.541, 0.293, 0.   , 0.396, 0.117, 0.167],
       [0.471, 0.92 , 0.525, 0.   , 0.   , 0.347, 0.254, 0.183],
       [0.059, 0.447, 0.541, 0.232, 0.111, 0.419, 0.038, 0.   ],
       [0.   , 0.688, 0.328, 0.354, 0.199, 0.642, 0.944, 0.2  ]])

In [ ]:
scaler=StandardScaler().fit(X)
rescaledX=scaler.transform(X)
rescaledX[0:5,:]

array([[ 0.64 ,  0.848,  0.15 ,  0.907, -0.693,  0.204,  0.468,  1.426],
       [-0.845, -1.123, -0.161,  0.531, -0.693, -0.684, -0.365, -0.191],
       [ 1.234,  1.944, -0.264, -1.288, -0.693, -1.103,  0.604, -0.106],
       [-0.845, -0.998, -0.161,  0.155,  0.123, -0.494, -0.921, -1.042],
       [-1.142,  0.504, -1.505,  0.907,  0.766,  1.41 ,  5.485, -0.02 ]])

In [ ]:
scaler=Normalizer().fit(X)
rescaledX=scaler.transform(X)
rescaledX[0:5,:]

array([[0.034, 0.828, 0.403, 0.196, 0.   , 0.188, 0.004, 0.28 ],
       [0.008, 0.716, 0.556, 0.244, 0.   , 0.224, 0.003, 0.261],
       [0.04 , 0.924, 0.323, 0.   , 0.   , 0.118, 0.003, 0.162],
       [0.007, 0.588, 0.436, 0.152, 0.622, 0.186, 0.001, 0.139],
       [0.   , 0.596, 0.174, 0.152, 0.731, 0.188, 0.01 , 0.144]])

In [ ]:
bin=Binarizer(threshold=0.0).fit(X)

In [ ]:
binaryX=bin.transform(X)

In [ ]:
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
skb=SelectKBest(score_func=f_classif, k=4).fit(X,Y)

In [ ]:
skb.scores_

array([ 39.67 , 213.162,   3.257,   4.304,  13.281,  71.772,  23.871,
        46.141])

In [ ]:
features=skb.transform(X)

In [ ]:
print(features[0:5,:])

[[  6.  148.   33.6  50. ]
 [  1.   85.   26.6  31. ]
 [  8.  183.   23.3  32. ]
 [  1.   89.   28.1  21. ]
 [  0.  137.   43.1  33. ]]


In [ ]:
model=LogisticRegression(solver='liblinear')

In [ ]:
rfe=RFE(model,n_features_to_select=3) 

In [ ]:
rfe.fit(X,Y)

RFE(estimator=LogisticRegression(solver='liblinear'), n_features_to_select=3)

In [ ]:
rfe.n_features_

3

In [ ]:
rfe.support_

array([ True, False, False, False, False,  True,  True, False])

In [ ]:
rfe.ranking_

array([1, 2, 3, 5, 6, 1, 1, 4])

In [ ]:
rfe.fit_transform(X,Y)

array([[ 6.   , 33.6  ,  0.627],
       [ 1.   , 26.6  ,  0.351],
       [ 8.   , 23.3  ,  0.672],
       ...,
       [ 5.   , 26.2  ,  0.245],
       [ 1.   , 30.1  ,  0.349],
       [ 1.   , 30.4  ,  0.315]])

In [ ]:
pca=PCA(n_components=3)

In [ ]:
fit=pca.fit(X)

In [ ]:
fit.explained_variance_ratio_

array([0.889, 0.062, 0.026])

In [ ]:
fit.components_

array([[-2.022e-03,  9.781e-02,  1.609e-02,  6.076e-02,  9.931e-01,
         1.401e-02,  5.372e-04, -3.565e-03],
       [-2.265e-02, -9.722e-01, -1.419e-01,  5.786e-02,  9.463e-02,
        -4.697e-02, -8.168e-04, -1.402e-01],
       [-2.246e-02,  1.434e-01, -9.225e-01, -3.070e-01,  2.098e-02,
        -1.324e-01, -6.400e-04, -1.255e-01]])

In [ ]:
pca.fit_transform(X)

array([[-75.715, -35.951,  -7.261],
       [-82.358,  28.908,  -5.497],
       [-74.631, -67.906,  19.462],
       ...,
       [ 32.113,   3.377,  -1.588],
       [-80.214, -14.186,  12.351],
       [-81.308,  21.621,  -8.153]])

In [ ]:
model=ExtraTreesClassifier(n_estimators=100)

In [ ]:
model.fit(X,Y)

ExtraTreesClassifier()

In [ ]:
print(model.feature_importances_)

[0.11  0.234 0.101 0.078 0.074 0.14  0.118 0.146]
